name: The Praxis Program
markdown: redcarpet
pygments: true
exclude: ['Rakefile', 'README.md', 'config.rb', 'Gemfile', 'Gemfile.lock', '_settings.yml', 'plugins']

domain: praxis.scholarslab.org
title: The Praxis Program
author: Scholars' Lab
email: praxis@collab.itc.virginia.edu