# standard jekyll configuration

permalink: date
pygments: true
exclude: ['Rakefile', 'README.md', 'config.rb']
markdown: rdiscount

# configuration required for some pages

domain: praxis.scholarslab.org 
title: The Praxis Program
author: Scholars' Lab
email: 

pages_dir: _pages/

# configuration for ehancements, uncomment to enable

# feedburner:
# id: feedburnerid

google_analytics:
  account: UA-12081576-3

# github:
# username: ghusername

# disqus:
# id: disqusid
